#!/usr/bin/env python3
import sys
import os
import re
from logic.parseSyntax import parseSyntax


#Maaf Ges, kodenya berantakan BANGET, cuman buat bahan gabut/iseng.

def jawaInterpreter():
    locateFile = sys.argv[1]

    check = locateFile.split(".")

    if check[1] != "jawa":
        print(locateFile + " " + "Bukan jawa language")
        return

    f = open(locateFile, 'r')

    fread = f.read()

    h = fread.split('\n')

    result = map(parseSyntax, h)

    res = list(result)

    ctoe = ""

    for r in res:
        ctoe += r + '\n'
    
    os.system("python3 -c '"+ctoe+"'")


jawaInterpreter()